services:

  app: 
    build: .
    ports:
      - '8000:8000'
  
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pomodoro


  